import pygame


COUNT_CELLS = 10
CELL_SIZE = 36
UNIT_SIZE = 72
WIDTH_MENU = CELL_SIZE * 6
SIZE_MAP = WIDTH_MAP, HEIGHT_MAP = CELL_SIZE * COUNT_CELLS, CELL_SIZE * COUNT_CELLS
SIZE = WIDTH, HEIGHT = WIDTH_MAP + WIDTH_MENU, HEIGHT_MAP
SCREEN = pygame.display.set_mode(SIZE)
